name: Download section of video and run script with ffmpeg
on:
  workflow_dispatch:
    inputs:
      videoUrl:
        description: 'Video URL'
        required: true
      startTime:
        description: 'Start time (in seconds)'
        required: true
      endTime:
        description: 'End time (in seconds)'
        required: true
      arg1:
        description: 'First argument for script'
        required: true
jobs:
  download-section-of-video-and-run-script-with-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Download section of video
        run: |
          yt-dlp -o output.mp4 -f 'bv*[ext=mp4][height=720]+ba' --download-sections "${{ github.event.inputs.startTime }}-${{ github.event.inputs.endTime }}" ${{ github.event.inputs.videoUrl }}
      - name: Run script
        run: |
          ./clipmaker.sh "${{ github.event.inputs.arg1 }}" 
      - name: Upload to Cloudflare R2 Storage
        run: |
           curl -X PUT "https://api.cloudflare.com/client/v4/accounts/c3d0463944e717492aaeae4f2dfdd184/r2/buckets/infraredclips/objects/output.mp4" \
           -H "Authorization: Bearer de3ad1541cf32e452b319dadd318588a12821b83582c3951ecab9573315" \
           -H "Content-Type: video/mp4" \
           --data-binary "@output.mp4"
      - name: Remove output files
        run: |
            rm output.mp4 output1.mp4
         
