name: Download section of video and run script with ffmpeg
on:
  workflow_dispatch:
    inputs:
      videoUrl:
        description: 'Video URL'
        required: true
      startTime:
        description: 'Start time (in seconds)'
        required: true
      endTime:
        description: 'End time (in seconds)'
        required: true
      arg1:
        description: 'First argument for script'
        required: true
jobs:
  download-section-of-video-and-run-script-with-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Download section of video
        run: |
          yt-dlp -o output.mp4 -f 22 --download-sections "*${{ github.event.inputs.startTime }}-${{ github.event.inputs.endTime }}" ${{ github.event.inputs.videoUrl }}
      - name: Run script
        run: |
          chmod +x ./clipmaker.sh
          ./clipmaker.sh "${{ github.event.inputs.arg1 }}" 
      - name: Upload to Cloudflare R2 Storage
        run: |
           curl -X PUT "https://api.cloudflare.com/client/v4/accounts/c3d0463944e717492aaeae4f2dfdd184/r2/buckets/infraredclips/objects/output.mp4" \
           -H "Authorization: Bearer 0cf0d70e2ecdcc6035d26025d364e09c 39f3558a2a2f94ae6c4643971ffd0e2640e4e8ff5475e8def5725177d488135a" \
           -H "Content-Type: video/mp4" \
           --data-binary "@output1.mp4"
      - name: Remove output files
        run: |
            rm output.mp4 output1.mp4
         
